module.exports = {
  content: [
    "./application/modules/**/*.php",
    "./assets/js/main.js",
  ],
  safelist: {
    standard: [
      "active", "show", "hide", "fade", "in", "out", "open", "close",
      "disabled", "loading", "error", "success", "visible", "hidden",
      "collapsed", "collapsing", "modal-open", "overflow-hidden",
    ],
    // Bootstrap dynamic classes
    patterns: [
      /^col-/,
      /^row/,
      /^d-/,
      /^flex-/,
      /^align-/,
      /^justify-/,
      /^m[tblrxy]?-/,
      /^p[tblrxy]?-/,
      /^g-/,
      /^gap-/,
      /^text-/,
      /^bg-/,
      /^border/,
      /^rounded/,
      /^w-/,
      /^h-/,
      /^fs-/,
      /^fw-/,
      /^lh-/,
      /^z-/,
      /^position-/,
      /^overflow-/,
      /^modal/,
      /^offcanvas/,
      /^dropdown/,
      /^collapse/,
      /^accordion/,
      /^nav-/,
      /^navbar/,
      /^btn/,
      /^form-/,
      /^input-/,
      /^alert-/,
      /^badge/,
      /^list-/,
      /^table/,
      /^card/,
      /^carousel/,
      /^tooltip/,
      /^popover/,
      /^placeholder/,
      /^spinner/,
      /^progress/,
      /^toast/,
      // AOS
      /^aos-/,
      /^data-aos/,
      // Swiper
      /^swiper/,
      // Fancybox
      /^f-/,
      /^fancybox/,
      /^is-/,
      /^has-/,
      // Animate.css
      /^animate__/,
      /^animated/,
      // Custom dynamic
      /^tab-/,
      /^ft-/,
      /^cc-/,
      /^cursor/,
    ],
  },
};
